Teemart/Controllers/AccountUserController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nhom9.Models;

namespace Nhom9.Controllers
{
    public class AccountUserController : Controller
    {
        Nhom9DB db = new Nhom9DB();
        // GET: AccountUser
        [HttpGet]
        public ActionResult ChangePassWord()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassWord(string oldpassword, string password)
        {
            TaiKhoanNguoiDung tk = (TaiKhoanNguoiDung)Session[Nhom9.Session.ConstaintUser.USER_SESSION];
            if(tk.MatKhau != oldpassword)
            {
                ModelState.AddModelError("ErrorUpdate","Mật khẩu cũ không đúng");
            }
            else
            {
                TaiKhoanNguoiDung edit = db.TaiKhoanNguoiDungs.Where(a => a.MaTK.Equals(tk.MaTK)).FirstOrDefault();
                edit.MatKhau = password;
                db.SaveChanges();
                Session[Nhom9.Session.ConstaintUser.USER_SESSION] = edit;
                ModelState.AddModelError("ErrorUpdate", "Đổi mật khẩu thành công!");
            }
            return View();
        }

        [HttpGet]
        public ActionResult UserInfor(int id)
        {
            TaiKhoanNguoiDung session = (TaiKhoanNguoiDung)Session[Nhom9.Session.ConstaintUser.USER_SESSION];
            if (session == null)
            {
                return RedirectToAction("PageNotFound","Error");
            }
            else
            {
                TaiKhoanNguoiDung tk = db.TaiKhoanNguoiDungs.Where(a => a.MaTK.Equals(id)).FirstOrDefault();
                return View(tk);
            }
        }
       

        [HttpPost]
        public ActionResult UserInfor([Bind(Include = "MaTK,Hoten,Diachi,,Email,Sodienthoai,Ngaysinh,Gioitinh")] TaiKhoanNguoiDung tk)
        {
            TaiKhoanNguoiDung edit = db.TaiKhoanNguoiDungs.Where(a => a.MaTK.Equals(tk.MaTK)).FirstOrDefault();
            try
            {
                edit.HoTen = tk.HoTen;
                edit.DiaChi = tk.DiaChi;
                edit.Email = tk.Email;
                edit.SoDienThoai = tk.SoDienThoai;
                edit.NgaySinh = tk.NgaySinh;
                edit.GioiTinh = tk.GioiTinh;
                db.SaveChanges();
                Session[Nhom9.Session.ConstaintUser.USER_SESSION] = edit;
            }
            catch(Exception)
            {
                ModelState.AddModelError("ErrorUpdate","Cập nhật thông tin không thành công ! Thử lại sau !");
            }
            return View(edit);
        }
    }
}

Teemart/Views/AccountUser/ChangePassWord.cshtml
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Breadcrumb Start -->
<div class="breadcrumb-area mt-30">
    <div class="container">
        <div class="breadcrumb">
            <ul class="d-flex align-items-center">
                <li>@Html.ActionLink("Trang chủ","Index","Home")</li>
                <li class="active">@Html.ActionLink("Đổi mật khẩu","ChangePassWord","AccountUser")</li>
            </ul>
        </div>
    </div>
    <!-- Container End -->
</div>
<!-- Breadcrumb End -->
<!-- Infor Page Start -->
<div class="register-account ptb-100 ptb-sm-60">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="register-title">
                    <h3 class="mb-10">Tài khoản</h3>
                </div>
            </div>
        </div>
        <!-- Row End -->
        <div class="row">
            <div class="col-sm-12">
                @using (Html.BeginForm("ChangePassWord", "AccountUser", FormMethod.Post, new { onsubmit = "return checkPass();" }))
                {
                    @Html.ValidationMessage("ErrorUpdate", new { @class = "text-danger", @id = "error-message" })
                    <br />
                    <hr />
                    <fieldset>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="accountOld">Mật khẩu cũ</label>
                            <div class="col-md-10">
                                <input type="password" name="oldpassword" required class="form-control" id="oldpassword" placeholder="Mật khẩu cũ">
                            </div>
                        </div>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="pwd">Mật khẩu mới</label>
                            <div class="col-md-10">
                                <input type="password" name="password" required class="form-control" id="password" placeholder="Mật khẩu mới">
                            </div>
                        </div>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="pwd-confirm">Xác nhận mật khẩu</label>
                            <div class="col-md-10">
                                <input type="password" class="form-control" required name="confirmpassword" id="confirmpassword" placeholder="Xác nhận mật khẩu">
                            </div>
                        </div>
                    </fieldset>

                    <div class="terms">
                        <div class="float-md-right">
                            <input type="submit" value="Đổi mật khẩu" class="return-customer-btn">
                        </div>
                    </div>
                }
            </div>
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>
<!-- Infor Page End -->
<script>
    function checkPass() {
        if (document.getElementById("password").value != document.getElementById("confirmpassword").value) {
            document.getElementById("error-message").innerHTML = "Mật khẩu không khớp";
            return false;
        }
        return true;
    }
</script>

Teemart/Views/AccountUser/UserInfor.cshtml
@model Nhom9.Models.TaiKhoanNguoiDung
@{
    ViewBag.Title = "Thông tin tài khoản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Breadcrumb Start -->
<div class="breadcrumb-area mt-30">
    <div class="container">
        <div class="breadcrumb">
            <ul class="d-flex align-items-center">
                <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                <li class="active">@Html.ActionLink("Thông tin tài khoản", "UserInfor", "AccountUser", new { id = Model.MaTK }, new { })</li>
            </ul>
        </div>
    </div>
    <!-- Container End -->
</div>
<!-- Breadcrumb End -->
<!-- Infor Page Start -->
<div class="register-account ptb-100 ptb-sm-60">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="register-title">
                    <h3 class="mb-10">Tài khoản</h3>
                </div>
            </div>
        </div>
        <!-- Row End -->
        <div class="row">
            <div class="col-sm-12">
                @using (Html.BeginForm("UserInfor", "AccountUser", FormMethod.Post, new { @id = "submit-form" }))
                {
                    @Html.ValidationMessage("ErrorUpdate", new { @class = "text-danger" })
                    <fieldset>
                        <input type="hidden" value="@Model.MaTK" name="matk" />
                        <legend>Thông tin tài khoản</legend>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="f-name">Họ và tên</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="hoten" placeholder="Họ và tên" value="@Model.HoTen" required>
                            </div>
                        </div>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="l-name">Địa chỉ</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="diachi" placeholder="Địa chỉ" value="@Model.DiaChi" required>
                            </div>
                        </div>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="email">Email</label>
                            <div class="col-md-10">
                                <input type="email" class="form-control" name="email" placeholder="Email" value="@Model.Email" required>
                            </div>
                        </div>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="number">Số điện thoại</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="sodienthoai" placeholder="Số điện thoại" value="@Model.SoDienThoai" required>
                            </div>
                        </div>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="date">Ngày sinh</label>
                            <div class="col-md-10">
                                <input type="date" class="form-control" name="ngaysinh" value="@Model.NgaySinh.ToString("yyyy-MM-dd")">
                            </div>
                        </div>
                        <div class="form-group d-md-flex align-items-md-center">
                            <label class="control-label col-md-2" for="gt">Giới tính</label>
                            <div class="col-md-10">
                                <input type="radio" checked="@Model.GioiTinh" name="gioitinh" value="true" id="Male"/>
                                <label for="Male">Nam</label>

                                <input type="radio" checked=@(!Model.GioiTinh) name="gioitinh" value="false" id="Female" />
                                <label for="Female" >Nữ</label>
                            </div>
                        </div>
                        <input type="hidden" name="trangthai" value="@Model.TrangThai" />
                    </fieldset>
                    <div class="terms">
                        <div class="float-md-right">
                            <input type="submit" value="Cập nhật" class="return-customer-btn">
                        </div>
                    </div>
                }
            </div>
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>
<!-- Infor Page End -->